name: CI/CD QA Pipeline

on:
  push:
    branches:
      - test

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-docker:latest .

      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-docker:latest

  deploy-to-ec2-instance-1:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST_1 }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "Pull, stop, and redeploy the Docker container"
            docker pull ${{ secrets.DOCKER_USERNAME }}/devops-docker:latest
            docker stop devops-docker || true
            docker rm devops-docker || true
            docker run -d --name devops-docker -p 80:80 ${{ secrets.DOCKER_USERNAME }}/devops-docker:latest
  # deploy-to-ec2-instance-2:
  #   needs: build-and-push-docker
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to EC2
  #       uses: appleboy/ssh-action@v0.1.10
  #       with:
  #         host: ${{ secrets.EC2_HOST_2 }}
  #         username: ${{ secrets.EC2_USER }}
  #         key: ${{ secrets.EC2_PRIVATE_KEY }}
  #         script: |
  #           echo "Pull, stop, and redeploy the Docker container"
  #           docker pull ${{ secrets.DOCKER_USERNAME }}/devops-docker:latest
  #           docker stop devops-docker || true
  #           docker rm devops-docker || true
  #           docker run -d --name devops-docker -p 80:80 ${{ secrets.DOCKER_USERNAME }}/devops-docker:latest            